.\" Man page for stikkit
.\" Licensed under BSD-like License.
.\" Created by Petr Bena
.\"
.TH Stikkit "Pastebin uploader" "User Manual"
.SH NAME
stikkit
\- run stikkit

.SH DESCRIPTION
Stikkit is an open source pastebin uploader for Stikked
.PP
.SH "AUTHOR"
Petr Bena
.br
Project home page: http://github.com/benapetr/stikkit
